development: &default
  adapter: mysql2
  database: team_work_dev
  username: root
  password: root
  host: localhost
  encoding: utf8
  port: 3306
  reconnect: true

test:
  <<: *default
  database: team_work_test

production:
  adapter: mysql2
  database: team_work_prod
  username: root
  password: root
  host: localhost
  encoding: utf8
  port: 3306
  reconnect: true
